export default defineEventHandler(async (event) => {
  const { name: queryName } = getQuery(event);
  const MAIN_URL = `https://restcountries.com/v3.1/name/${queryName}`;

  const data = await fetch(MAIN_URL);
  const dataJSON = await data.json();

  const {
    flags,
    name,
    population,
    region,
    subregion,
    capital,
    tld,
    currencies,
    languages,
  } = dataJSON[0];

  const response = {
    flag: flags.png,
    header: name.common,
    nativeName: '',
    population: population
      .toString()
      .replace(/\B(?=(\d{3})+(?!\d))/g, ','),
    region: region,
    subRegion: subregion,
    capital: capital[0],
    topLevelDomain: tld,
    currencies: '',
    languages: [''],
  };

  console.log('server', response);

  const obj1 = {
    name: {
      common: 'Argentina',
      official: 'Argentine Republic',
      nativeName: {
        grn: { official: 'Argentine Republic', common: 'Argentina' },
        spa: { official: 'República Argentina', common: 'Argentina' },
      },
    },
    tld: ['.ar'],
    cca2: 'AR',
    ccn3: '032',
    cca3: 'ARG',
    cioc: 'ARG',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { ARS: { name: 'Argentine peso', symbol: '$' } },
    idd: { root: '+5', suffixes: ['4'] },
    capital: ['Buenos Aires'],
    altSpellings: ['AR', 'Argentine Republic', 'República Argentina'],
    region: 'Americas',
    subregion: 'South America',
    languages: { grn: 'Guaraní', spa: 'Spanish' },
    translations: {
      ara: { official: 'جمهورية الأرجنتين', common: 'الأرجنتين' },
      bre: { official: "Republik Arc'hantina", common: "Arc'hantina" },
      ces: { official: 'Argentinská republika', common: 'Argentina' },
      cym: { official: 'Gweriniaeth yr Ariannin', common: 'Ariannin' },
      deu: { official: 'Argentinische Republik', common: 'Argentinien' },
      est: { official: 'Argentina Vabariik', common: 'Argentina' },
      fin: { official: 'Argentiinan tasavalta', common: 'Argentiina' },
      fra: { official: 'République argentine', common: 'Argentine' },
      hrv: { official: 'Argentinski Republika', common: 'Argentina' },
      hun: { official: 'Argentin Köztársaság', common: 'Argentína' },
      ita: { official: 'Repubblica Argentina', common: 'Argentina' },
      jpn: { official: 'アルゼンチン共和国', common: 'アルゼンチン' },
      kor: { official: '아르헨티나 공화국', common: '아르헨티나' },
      nld: { official: 'Argentijnse Republiek', common: 'Argentinië' },
      per: { official: 'جمهوری آرژانتین', common: 'آرژانتین' },
      pol: { official: 'Republika Argentyńska', common: 'Argentyna' },
      por: { official: 'República Argentina', common: 'Argentina' },
      rus: { official: 'Аргентинская Республика', common: 'Аргентина' },
      slk: { official: 'Argentínska republika', common: 'Argentína' },
      spa: { official: 'República Argentina', common: 'Argentina' },
      swe: { official: 'Republiken Argentina', common: 'Argentina' },
      tur: { official: 'Arjantin Cumhuriyeti', common: 'Arjantin' },
      urd: { official: 'جمہوریہ ارجنٹائن', common: 'ارجنٹائن' },
      zho: { official: '阿根廷共和国', common: '阿根廷' },
    },
    latlng: [-34, -64],
    landlocked: false,
    borders: ['BOL', 'BRA', 'CHL', 'PRY', 'URY'],
    area: 2780400,
    demonyms: {
      eng: { f: 'Argentine', m: 'Argentine' },
      fra: { f: 'Argentine', m: 'Argentin' },
    },
    flag: '🇦🇷',
    maps: {
      googleMaps: 'https://goo.gl/maps/Z9DXNxhf2o93kvyc6',
      openStreetMaps: 'https://www.openstreetmap.org/relation/286393',
    },
    population: 45376763,
    gini: { 2019: 42.9 },
    fifa: 'ARG',
    car: { signs: ['RA'], side: 'right' },
    timezones: ['UTC-03:00'],
    continents: ['South America'],
    flags: {
      png: 'https://flagcdn.com/w320/ar.png',
      svg: 'https://flagcdn.com/ar.svg',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/ar.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/ar.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-34.58, -58.67] },
    postalCode: { format: '@####@@@', regex: '^([A-Z]\\d{4}[A-Z]{3})$' },
  };

  const obj = {
    name: {
      common: 'Belgium',
      official: 'Kingdom of Belgium',
      nativeName: {
        deu: { official: 'Königreich Belgien', common: 'Belgien' },
        fra: { official: 'Royaume de Belgique', common: 'Belgique' },
        nld: { official: 'Koninkrijk België', common: 'België' },
      },
    },
    tld: ['.be'],
    cca2: 'BE',
    ccn3: '056',
    cca3: 'BEL',
    cioc: 'BEL',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    idd: { root: '+3', suffixes: ['2'] },
    capital: ['Brussels'],
    altSpellings: [
      'BE',
      'België',
      'Belgie',
      'Belgien',
      'Belgique',
      'Kingdom of Belgium',
      'Koninkrijk België',
      'Royaume de Belgique',
      'Königreich Belgien',
    ],
    region: 'Europe',
    subregion: 'Western Europe',
    languages: { deu: 'German', fra: 'French', nld: 'Dutch' },
    translations: {
      ara: { official: 'مملكة بلجيكا', common: 'بلجيكا' },
      bre: { official: 'Rouantelezh Belgia', common: 'Belgia' },
      ces: { official: 'Belgické království', common: 'Belgie' },
      cym: { official: 'Teyrnas Gwlad Belg', common: 'Gwlad Belg' },
      deu: { official: 'Königreich Belgien', common: 'Belgien' },
      est: { official: 'Belgia Kuningriik', common: 'Belgia' },
      fin: { official: 'Belgian kuningaskunta', common: 'Belgia' },
      fra: { official: 'Royaume de Belgique', common: 'Belgique' },
      hrv: { official: 'Kraljevina Belgija', common: 'Belgija' },
      hun: { official: 'Belga Királyság', common: 'Belgium' },
      ita: { official: 'Regno del Belgio', common: 'Belgio' },
      jpn: { official: 'ベルギー王国', common: 'ベルギー' },
      kor: { official: '벨기에 왕국', common: '벨기에' },
      nld: { official: 'Koninkrijk België', common: 'België' },
      per: { official: 'پادشاهی بلژیک', common: 'بلژیک' },
      pol: { official: 'Królestwo Belgii', common: 'Belgia' },
      por: { official: 'Reino da Bélgica', common: 'Bélgica' },
      rus: { official: 'Королевство Бельгия', common: 'Бельгия' },
      slk: { official: 'Belgické kráľovstvo', common: 'Belgicko' },
      spa: { official: 'Reino de Bélgica', common: 'Bélgica' },
      swe: { official: 'Konungariket Belgien', common: 'Belgien' },
      tur: { official: 'Belçika Krallığı', common: 'Belçika' },
      urd: { official: 'مملکتِ بلجئیم', common: 'بلجئیم' },
      zho: { official: '比利时王国', common: '比利时' },
    },
    latlng: [50.83333333, 4],
    landlocked: false,
    borders: ['FRA', 'DEU', 'LUX', 'NLD'],
    area: 30528,
    demonyms: {
      eng: { f: 'Belgian', m: 'Belgian' },
      fra: { f: 'Belge', m: 'Belge' },
    },
    flag: '🇧🇪',
    maps: {
      googleMaps: 'https://goo.gl/maps/UQQzat85TCtPRXAL8',
      openStreetMaps: 'https://www.openstreetmap.org/relation/52411',
    },
    population: 11555997,
    gini: { 2018: 27.2 },
    fifa: 'BEL',
    car: { signs: ['B'], side: 'right' },
    timezones: ['UTC+01:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/be.png',
      svg: 'https://flagcdn.com/be.svg',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/be.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/be.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [50.83, 4.33] },
    postalCode: { format: '####', regex: '^(\\d{4})$' },
  };

  return response[0];
});
